spark.master                     spark://spark-master:7077
spark.eventLog.enabled           true
spark.eventLog.dir               hdfs://namenode:9000/spark-events
spark.history.fs.logDirectory    hdfs://namenode:9000/spark-events
spark.hadoop.fs.defaultFS        hdfs://namenode:9000
